version: "{branch}-{build}"
environment:
 PY_PYTHON: 2.7-32
install:
  - py -m pip install markdown
  

build_script:
  - PY scons.py

artifacts:
  - path: '*.nvda-addon'
    name: "Version  {}, revision{build}"
    type: application/x-nvda-addon
